# This is a sample production config (to be deployed in the WEB-INF directory).
# This is the same as what Google Registry runs in production, except with
# placeholders for Google-specific settings.

appEngine:
  projectId: placeholder
  # Set to true if running against local servers (localhost)
  isLocal: false
  # The "<service>-dot-" prefix is used on the project ID in this URL in order
  # to get around an issue with double-wildcard SSL certs.
  defaultServiceUrl: https://domain-registry-placeholder.appspot.com
  backendServiceUrl: https://backend-dot-domain-registry-placeholder.appspot.com
  toolsServiceUrl: https://tools-dot-domain-registry-placeholder.appspot.com
  pubapiServiceUrl: https://pubapi-dot-domain-registry-placeholder.appspot.com

gSuite:
  domainName: placeholder
  outgoingEmailDisplayName: placeholder
  outgoingEmailAddress: placeholder
  adminAccountEmailAddress: placeholder
  supportGroupEmailAddress: placeholder

registryPolicy:
  contactAndHostRoidSuffix: placeholder
  productName: placeholder
  greetingServerId: placeholder
  registrarChangesNotificationEmailAddresses:
    - placeholder
    - placeholder
  defaultRegistrarWhoisServer: placeholder
  tmchCaMode: PRODUCTION
  tmchCrlUrl: http://crl.icann.org/tmch.crl
  tmchMarksDbUrl: https://ry.marksdb.org
  checkApiServletClientId: placeholder
  registryAdminClientId: placeholder
  whoisDisclaimer: |
    multi-line
    placeholder

icannReporting:
  icannTransactionsReportingUploadUrl: https://ry-api.icann.org/report/registrar-transactions
  icannActivityReportingUploadUrl: https://ry-api.icann.org/report/registry-functions-activity

oAuth:
  allowedOauthClientIds:
    - placeholder.apps.googleusercontent.com
    - placeholder-for-proxy

rde:
  reportUrlPrefix: https://ry-api.icann.org/report/registry-escrow-report
  uploadUrl: sftp://placeholder@sftpipm2.ironmountain.com/Outbox
  sshIdentityEmailAddress: placeholder

registrarConsole:
  logoFilename: placeholder
  supportPhoneNumber: placeholder
  supportEmailAddress: placeholder
  announcementsEmailAddress: placeholder
  integrationEmailAddress: placeholder
  technicalDocsUrl: https://drive.google.com/drive/folders/placeholder

misc:
  sheetExportId: placeholder

cloudDns:
  rootUrl: null
  servicePath: null

keyring:
  activeKeyring: KMS
  kms:
    projectId: placeholder

registryTool:
  clientId: placeholder.apps.googleusercontent.com
  clientSecret: placeholder
