# This is the configuration file used by unit tests. These values ARE NOT
# SUITABLE for use in a real deployed environment.

registryPolicy:
  registrarChangesNotificationEmailAddresses:
    - notification@test.example
    - notification2@test.example
  defaultRegistrarWhoisServer: whois.nic.fakewhois.example
  reservedTermsExportDisclaimer: |
    Disclaimer line 1.
    Line 2 is this 1.

datastore:
  commitLogBucketsNum: 3
  eppResourceIndexBucketsNum: 3
  baseOfyRetryMillis: 0

caching:
  singletonCacheRefreshSeconds: 0
  domainLabelCachingSeconds: 0
  singletonCachePersistSeconds: 0
  staticPremiumListMaxCachedEntries: 50
  eppResourceCachingEnabled: true
  eppResourceCachingSeconds: 0

# Remove the support G Suite group, because we don't want to try connecting to G Suite servers from
# tests
gSuite:
  supportGroupEmailAddress:

misc:
  # We would rather have failures than timeouts, so reduce the number of retries
  transientFailureRetries: 3
